/* Main.c file generated by New Project wizard
 *
 * Created:   Sun May 8 2022
 * Processor: PIC16F84A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
__CONFIG(FOSC_HS & WDTE_OFF & PWRTE_ON & CP_OFF);

#define _XTAL_FREQ 3276800

void osvezi();
void upisi();
void prikaz(unsigned char);
unsigned char cifra0 = 0;
unsigned char status = 0;
unsigned char cifra1 = 0;
unsigned char brojac_visa = 0;
unsigned char brojac_niza = 0;

static unsigned char rng_state = 57;
unsigned char rng_next() {
    rng_state ^= (rng_state << 3);
    rng_state ^= (rng_state >> 7);
    rng_state ^= (rng_state << 5);
    return rng_state - 1;
}

void main(void)
{
    TRISA=0;
    TRISB=0x01;

    upisi();
    PORTB=0x00;
    PORTA=0x00;

    INTCON = 0x30;
    INTCONbits.GIE = 1;

    OPTION_REG=0xC2;

    while (1)
    {

    }
}

void prikaz(unsigned char cifra)
{
    EEADR = cifra + 2;
    EECON1bits.RD=1;
    PORTB = EEDATA;
}
void upisi() 
{
    int i = 0;
    int j = 2;
    static const int codes[]={ 0x80, 0xF2, 0x48, 0x60, 0x32, 0x24, 0x04, 0xF0, 0x00, 0x20 };
    for (i,j; i < 10; i++, j++) 
    {
        EEADR=j;
        EEDATA=codes[i];
        EECON1bits.WREN=1;
        EECON2=0x55;
        EECON2=0xAA;
        EECON1bits.WR=1;
        __delay_ms(10);
    }
}

void osvezi()
{
    static unsigned char disp = 0;
    if (disp){
        if (status == 2) {
            brojac_niza++;
            if (brojac_niza == 100) {
                brojac_niza=0;
                brojac_visa++;
            }
        }
        PORTAbits.RA1=1;
        PORTAbits.RA0=0;
        prikaz(cifra0);
        disp=0;
    }
    else {
        PORTAbits.RA0=1;
        PORTAbits.RA1=0;
        prikaz(cifra1);
        disp=1;
    }
}

void interrupt prekid(void) 
{
    if(INTCONbits.INTF==1)
    {
        if (status == 0) {
            status = 1;
            cifra0 = rng_next() % 10;
            cifra1 = rng_next() % 10;
        }
        else if (status == 1) {
            status = 2;
        }
        else {
            status = 0;
        }
        INTCONbits.INTF=0;
    }
    else if (INTCONbits.T0IF == 1){
        if (brojac_visa == 4 && status == 2) {
            if (cifra0 > 0) cifra0--;
            else if (cifra1 > 0) {
                cifra0=9;
                cifra1--;
            }
            else {
                status = 0;
            }
            brojac_visa = brojac_niza = 0;
        } 
        osvezi();
        INTCONbits.T0IF=0;
    }
}